version: '3.8'
services:
  garmin-listener:
    build: .
    ports:
      - "${GARMIN_PORT}:8085"
    networks:
      - garmin_listener_network

networks:
  garmin_listener_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.1.224/28
          gateway: 172.80.1.225